version: "3"

services:
  app:
    container_name: schedula_core
    image: schedula/core
    build: .
    volumes:
      - ".:/code/"
    ports:
      - "3002:3000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - NODE_ENV=DEVELOPMENT
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_DB=schedula_core
      - DATABASE_PORT=5432

  postgres:
    image: postgres:latest
    container_name: schedula_core_db
    ports:
      - "5105:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schedula_core

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "schedula@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "schedula123!"
    ports:
      - "16545:80"
    depends_on:
      - postgres